#pragma once
#ifndef INCLUDED_MOUSE_BUTTON_STATE_H_
#define INCLUDED_MOUSE_BUTTON_STATE_H_

enum MouseButtonState {
	BUTTON_DOWN,
	BUTTON_DOWN_KEEP,
	BUTTON_UP,
	BUTTON_UP_KEEP, 
	UNKNOWN
};


#endif // !INCLUDED_MOUSE_BUTTONSTATE_H_
